# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f9a228fecbcbfb85f7a7b9b81bc9adf9eabde486b10a80553181813b0b1d3a9952003a97e8ba3eb15d881a21853c6550658a07c01a3829f1c3ba2695cd05156

test:
  secret_key_base: 7f04228aa59e9de4eac572856c41b5631a13ce1c8cf42b8f39d86bec1a45775bfc057cdc0e6fd62b019209bfea231925e37747ee6d0875554994f780fe7f00c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
