durations = Duration.create([{ name: "monthly" }, { name: "weekly" }, { name: "daily" }])
categories = Category.create([{ name: "Rent" }, {name: "Bills"}, {name: "Food/Groceries"}, {name: "Transportation"}, {name: "Recreation"}, {name: "Pay"}, {name: "Other"}])
transactions = Transaction.create([
                                    { name: "Rent",
                                      amount: 1600,
                                      description: "Gotta pay rent",
                                      category_id: 1,
                                      type: "Expense",
                                      date: DateTime.parse("01/01/2014"),
                                      user_id: 1
                                    },
                                    { name: "Internet",
                                      amount: 55,
                                      description: "High speed",
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("03/01/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 8.50,
                                      description: "Lunch special",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("02/01/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2000,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("11/01/2014"),
                                      user_id: 1
                                    },
                                    { name: "Toothpaste",
                                      amount: 2,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("10/01/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas",
                                      amount: 45,
                                      description: "Should have taken the T",
                                      category_id: 4,
                                      type: "Expense",
                                      date: DateTime.parse("18/01/2014"),
                                      user_id: 1
                                    },
                                    { name: "Oil change",
                                      amount: 25,
                                      category_id: 4,
                                      type: "Expense",
                                      date: DateTime.parse("20/01/2014"),
                                      user_id: 1
                                    },
                                    { name: "Movies",
                                      amount: 23.50,
                                      description: "Guardians of Galaxy",
                                      category_id: 5,
                                      type: "Expense",
                                      date: DateTime.parse("30/01/2014"),
                                      user_id: 1
                                    },
                                    { name: "Movies",
                                      amount: 23.50,
                                      description: "Guardians of Galaxy (again)",
                                      category_id: 5,
                                      type: "Expense",
                                      date: DateTime.parse("15/01/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2000,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("05/01/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 11,
                                      description: "Tacos",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("04/01/2014"),
                                      user_id: 1
                                    },
                                    { name: "New jacket",
                                      amount: 89.78,
                                      category_id: 7,
                                      type: "Expense",
                                      date: DateTime.parse("08/01/2014"),
                                      user_id: 1
                                    },
                                    { name: "Groceries",
                                      amount: 97,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("30/01/2014"),
                                      user_id: 1
                                    },
                                    { name: "Electrity",
                                      amount: 65,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("22/01/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas bill",
                                      amount: 75,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("25/01/2014"),
                                      user_id: 1
                                    },
                                    { name: "Sold couch",
                                      amount: 80,
                                      category_id: 7,
                                      type: "Income",
                                      date: DateTime.parse("10/01/2014"),
                                      user_id: 1
                                    },
                                    { name: "Rent",
                                      amount: 1600,
                                      description: "Gotta pay rent",
                                      category_id: 1,
                                      type: "Expense",
                                      date: DateTime.parse("01/02/2014"),
                                      user_id: 1
                                    },
                                    { name: "Internet",
                                      amount: 55,
                                      description: "High speed",
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("03/02/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 6.50,
                                      description: "Lunch special",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("02/02/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2000,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("11/02/2014"),
                                      user_id: 1
                                    },
                                    { name: "Soap",
                                      amount: 4,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("10/02/2014"),
                                      user_id: 1
                                    },
                                    { name: "Bus Pass",
                                      amount: 75,
                                      description: "Gonna save money",
                                      category_id: 4,
                                      type: "Expense",
                                      date: DateTime.parse("01/02/2014"),
                                      user_id: 1
                                    },
                                    { name: "Movies",
                                      amount: 12.50,
                                      description: "Fun",
                                      category_id: 5,
                                      type: "Expense",
                                      date: DateTime.parse("28/02/2014"),
                                      user_id: 1
                                    },
                                    { name: "Dinner",
                                      amount: 50.23,
                                      description: "Valentines Day",
                                      category_id: 5,
                                      type: "Expense",
                                      date: DateTime.parse("14/02/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2000,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("05/02/2014"),
                                      user_id: 1
                                    },
                                    { name: "Groceries",
                                      amount: 65,
                                      description: "Bread and whatnot",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("04/02/2014"),
                                      user_id: 1
                                    },
                                    { name: "New shoes",
                                      amount: 60,
                                      category_id: 7,
                                      type: "Expense",
                                      date: DateTime.parse("08/02/2014"),
                                      user_id: 1
                                    },
                                    { name: "Groceries",
                                      amount: 25,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("28/02/2014"),
                                      user_id: 1
                                    },
                                    { name: "Electrity",
                                      amount: 65,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("22/02/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas bill",
                                      amount: 75,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("25/02/2014"),
                                      user_id: 1
                                    },
                                    { name: "New couch",
                                      amount: 180,
                                      category_id: 7,
                                      type: "Expense",
                                      date: DateTime.parse("10/02/2014"),
                                      user_id: 1
                                    },
                                    { name: "Rent",
                                      amount: 1600,
                                      description: "Gotta pay rent",
                                      category_id: 1,
                                      type: "Expense",
                                      date: DateTime.parse("01/03/2014"),
                                      user_id: 1
                                    },
                                    { name: "Internet",
                                      amount: 55,
                                      description: "High speed",
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("03/03/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch meat",
                                      amount: 15,
                                      description: "Lunch for two weeks",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("02/03/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2000,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("11/03/2014"),
                                      user_id: 1
                                    },
                                    { name: "Bus pass",
                                      amount: 45,
                                      category_id: 4,
                                      type: "Expense",
                                      date: DateTime.parse("18/03/2014"),
                                      user_id: 1
                                    },
                                    { name: "Candle Workshop",
                                      amount: 52,
                                      description: "Learned to make candles",
                                      category_id: 5,
                                      type: "Expense",
                                      date: DateTime.parse("30/03/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2000,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("05/03/2014"),
                                      user_id: 1
                                    },
                                    { name: "Dinner",
                                      amount: 23,
                                      description: "Tacos",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("04/03/2014"),
                                      user_id: 1
                                    },
                                    { name: "Socks",
                                      amount: 12,
                                      category_id: 7,
                                      type: "Expense",
                                      date: DateTime.parse("08/03/2014"),
                                      user_id: 1
                                    },
                                    { name: "Groceries",
                                      amount: 45,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("10/03/2014"),
                                      user_id: 1
                                    },
                                    { name: "Electrity",
                                      amount: 65,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("22/03/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas bill",
                                      amount: 75,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("25/03/2014"),
                                      user_id: 1
                                    },
                                    { name: "Birthday cash",
                                      amount: 100,
                                      category_id: 7,
                                      type: "Income",
                                      date: DateTime.parse("01/03/2014"),
                                      user_id: 1
                                    },
                                    { name: "Rent",
                                      amount: 1600,
                                      description: "Gotta pay rent",
                                      category_id: 1,
                                      type: "Expense",
                                      date: DateTime.parse("01/04/2014"),
                                      user_id: 1
                                    },
                                    { name: "Internet",
                                      amount: 55,
                                      description: "High speed",
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("03/04/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 15,
                                      description: "Overpriced",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("02/04/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2000,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("11/04/2014"),
                                      user_id: 1
                                    },
                                    { name: "Tootbrush",
                                      amount: 2,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("10/04/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas",
                                      amount: 45,
                                      description: "No bus pass this month",
                                      category_id: 4,
                                      type: "Expense",
                                      date: DateTime.parse("18/04/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas",
                                      amount: 34,
                                      category_id: 4,
                                      type: "Expense",
                                      date: DateTime.parse("02/04/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2000,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("05/04/2014"),
                                      user_id: 1
                                    },
                                    { name: "Dinner with friends",
                                      amount: 38,
                                      description: "Chinese food",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("04/04/2014"),
                                      user_id: 1
                                    },
                                    { name: "Groceries",
                                      amount: 107,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("30/04/2014"),
                                      user_id: 1
                                    },
                                    { name: "Electrity",
                                      amount: 65,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("22/04/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas bill",
                                      amount: 75,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("25/04/2014"),
                                      user_id: 1
                                    },
                                    { name: "Found some cash",
                                      amount: 20,
                                      category_id: 7,
                                      type: "Income",
                                      date: DateTime.parse("10/04/2014"),
                                      user_id: 1
                                    },
                                    { name: "Rent",
                                      amount: 1600,
                                      description: "Gotta pay rent",
                                      category_id: 1,
                                      type: "Expense",
                                      date: DateTime.parse("01/05/2014"),
                                      user_id: 1
                                    },
                                    { name: "Internet",
                                      amount: 55,
                                      description: "High speed",
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("03/05/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 4.50,
                                      description: "Lunch special",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("02/05/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2000,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("11/05/2014"),
                                      user_id: 1
                                    },
                                    { name: "Movies",
                                      amount: 23.50,
                                      category_id: 5,
                                      type: "Expense",
                                      date: DateTime.parse("30/05/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2000,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("05/05/2014"),
                                      user_id: 1
                                    },
                                    { name: "Breakfast with bro",
                                      amount: 11,
                                      description: "Pancakes",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("04/05/2014"),
                                      user_id: 1
                                    },
                                    { name: "New shirts",
                                      amount: 44.50,
                                      category_id: 7,
                                      type: "Expense",
                                      date: DateTime.parse("08/05/2014"),
                                      user_id: 1
                                    },
                                    { name: "Groceries",
                                      amount: 78,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("30/05/2014"),
                                      user_id: 1
                                    },
                                    { name: "Electrity",
                                      amount: 65,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("22/05/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas bill",
                                      amount: 75,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("25/05/2014"),
                                      user_id: 1
                                    },
                                    { name: "Rent",
                                      amount: 1600,
                                      description: "Gotta pay rent",
                                      category_id: 1,
                                      type: "Expense",
                                      date: DateTime.parse("01/06/2014"),
                                      user_id: 1
                                    },
                                    { name: "Internet",
                                      amount: 55,
                                      description: "High speed",
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("03/06/2014"),
                                      user_id: 1
                                    },
                                    { name: "Birthday present",
                                      amount: 20,
                                      description: "For Michael",
                                      category_id: 7,
                                      type: "Expense",
                                      date: DateTime.parse("03/06/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2000,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("11/06/2014"),
                                      user_id: 1
                                    },
                                    { name: "Toothpaste",
                                      amount: 2,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("10/06/2014"),
                                      user_id: 1
                                    },
                                    { name: "Bus pass",
                                      amount: 75,
                                      category_id: 4,
                                      type: "Expense",
                                      date: DateTime.parse("18/06/2014"),
                                      user_id: 1
                                    },
                                    { name: "Movies",
                                      amount: 20.50,
                                      description: "No popcorn",
                                      category_id: 5,
                                      type: "Expense",
                                      date: DateTime.parse("30/06/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2200,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("05/06/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 11,
                                      description: "Tacos",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("04/06/2014"),
                                      user_id: 1
                                    },
                                    { name: "Summer shoes",
                                      amount: 50,
                                      category_id: 7,
                                      type: "Expense",
                                      date: DateTime.parse("08/06/2014"),
                                      user_id: 1
                                    },
                                    { name: "Groceries",
                                      amount: 108,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("30/06/2014"),
                                      user_id: 1
                                    },
                                    { name: "Electrity",
                                      amount: 65,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("22/06/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas bill",
                                      amount: 75,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("25/06/2014"),
                                      user_id: 1
                                    },
                                    { name: "Savings",
                                      amount: 100,
                                      category_id: 7,
                                      type: "Expense",
                                      date: DateTime.parse("10/06/2014"),
                                      user_id: 1
                                    },
                                    { name: "Rent",
                                      amount: 1600,
                                      description: "Gotta pay rent",
                                      category_id: 1,
                                      type: "Expense",
                                      date: DateTime.parse("01/07/2014"),
                                      user_id: 1
                                    },
                                    { name: "Internet",
                                      amount: 55,
                                      description: "High speed",
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("03/07/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 8.50,
                                      description: "Lunch special",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("02/07/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2200,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("11/07/2014"),
                                      user_id: 1
                                    },
                                    { name: "Bus pass",
                                      amount: 75,
                                      category_id: 4,
                                      type: "Expense",
                                      date: DateTime.parse("18/07/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2200,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("05/07/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 11,
                                      description: "Pizza",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("04/07/2014"),
                                      user_id: 1
                                    },
                                    { name: "Groceries",
                                      amount: 67,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("30/07/2014"),
                                      user_id: 1
                                    },
                                    { name: "Electrity",
                                      amount: 65,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("22/07/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas bill",
                                      amount: 75,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("25/07/2014"),
                                      user_id: 1
                                    },
                                    { name: "Rent",
                                      amount: 1600,
                                      description: "Gotta pay rent",
                                      category_id: 1,
                                      type: "Expense",
                                      date: DateTime.parse("01/08/2014"),
                                      user_id: 1
                                    },
                                    { name: "Internet",
                                      amount: 55,
                                      description: "High speed",
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("03/08/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 11.50,
                                      description: "Pasta",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("02/08/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2200,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("11/08/2014"),
                                      user_id: 1
                                    },
                                    { name: "Shampoo",
                                      amount: 6,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("10/08/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas",
                                      amount: 85,
                                      description: "Should have taken the T",
                                      category_id: 4,
                                      type: "Expense",
                                      date: DateTime.parse("18/08/2014"),
                                      user_id: 1
                                    },
                                    { name: "Redsox game",
                                      amount: 75.50,
                                      category_id: 5,
                                      type: "Expense",
                                      date: DateTime.parse("30/08/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2200,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("05/08/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 11,
                                      description: "Tacos",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("04/08/2014"),
                                      user_id: 1
                                    },
                                    { name: "Groceries",
                                      amount: 99,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("30/08/2014"),
                                      user_id: 1
                                    },
                                    { name: "Electrity",
                                      amount: 65,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("22/08/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas bill",
                                      amount: 75,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("25/08/2014"),
                                      user_id: 1
                                    },
                                    { name: "Rent",
                                      amount: 1600,
                                      description: "Gotta pay rent",
                                      category_id: 1,
                                      type: "Expense",
                                      date: DateTime.parse("01/09/2014"),
                                      user_id: 1
                                    },
                                    { name: "Internet",
                                      amount: 55,
                                      description: "High speed",
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("03/09/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 8.50,
                                      description: "Lunch special",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("02/09/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2200,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("11/09/2014"),
                                      user_id: 1
                                    },
                                    { name: "Bus pass",
                                      amount: 75,
                                      category_id: 4,
                                      type: "Expense",
                                      date: DateTime.parse("18/09/2014"),
                                      user_id: 1
                                    },
                                    { name: "Redsox game",
                                      amount: 60,
                                      description: "Go Sox",
                                      category_id: 5,
                                      type: "Expense",
                                      date: DateTime.parse("30/09/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2200,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("05/09/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 11,
                                      description: "Tacos",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("04/09/2014"),
                                      user_id: 1
                                    },
                                    { name: "Groceries",
                                      amount: 86,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("30/09/2014"),
                                      user_id: 1
                                    },
                                    { name: "Electrity",
                                      amount: 65,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("22/09/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas bill",
                                      amount: 75,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("25/09/2014"),
                                      user_id: 1
                                    },
                                    { name: "Rent",
                                      amount: 1600,
                                      description: "Gotta pay rent",
                                      category_id: 1,
                                      type: "Expense",
                                      date: DateTime.parse("01/10/2014"),
                                      user_id: 1
                                    },
                                    { name: "Internet",
                                      amount: 55,
                                      description: "High speed",
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("03/10/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 8.50,
                                      description: "Lunch special",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("02/10/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2200,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("11/10/2014"),
                                      user_id: 1
                                    },
                                    { name: "Toothpaste",
                                      amount: 2,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("10/10/2014"),
                                      user_id: 1
                                    },
                                    { name: "Bus pass",
                                      amount: 75,
                                      description: "Shouldn't have taken the T",
                                      category_id: 4,
                                      type: "Expense",
                                      date: DateTime.parse("18/10/2014"),
                                      user_id: 1
                                    },
                                    { name: "Movies",
                                      amount: 25.50,
                                      category_id: 5,
                                      type: "Expense",
                                      date: DateTime.parse("30/10/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2200,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("05/10/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 11,
                                      description: "Tacos",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("04/10/2014"),
                                      user_id: 1
                                    },
                                    { name: "Groceries",
                                      amount: 90,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("30/10/2014"),
                                      user_id: 1
                                    },
                                    { name: "Electrity",
                                      amount: 65,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("22/10/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas bill",
                                      amount: 75,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("25/10/2014"),
                                      user_id: 1
                                    },
                                    { name: "Sold chair",
                                      amount: 10,
                                      category_id: 7,
                                      type: "Income",
                                      date: DateTime.parse("10/10/2014"),
                                      user_id: 1
                                    },
                                    { name: "Rent",
                                      amount: 1600,
                                      description: "Gotta pay rent",
                                      category_id: 1,
                                      type: "Expense",
                                      date: DateTime.parse("01/11/2014"),
                                      user_id: 1
                                    },
                                    { name: "Internet",
                                      amount: 55,
                                      description: "High speed",
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("03/11/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 8.50,
                                      description: "Lunch special",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("02/11/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2400,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("11/11/2014"),
                                      user_id: 1
                                    },
                                    { name: "Turkey",
                                      amount: 25,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("10/11/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas",
                                      amount: 65,
                                      description: "Should have taken the T",
                                      category_id: 4,
                                      type: "Expense",
                                      date: DateTime.parse("18/11/2014"),
                                      user_id: 1
                                    },
                                    { name: "Car maintenance",
                                      amount: 200,
                                      category_id: 4,
                                      type: "Expense",
                                      date: DateTime.parse("20/11/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2400,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("05/11/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 11,
                                      description: "Pie",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("04/11/2014"),
                                      user_id: 1
                                    },
                                    { name: "Groceries",
                                      amount: 127,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("30/11/2014"),
                                      user_id: 1
                                    },
                                    { name: "Electrity",
                                      amount: 65,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("22/11/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas bill",
                                      amount: 75,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("25/11/2014"),
                                      user_id: 1
                                    },
                                    { name: "Rent",
                                      amount: 1600,
                                      description: "Gotta pay rent",
                                      category_id: 1,
                                      type: "Expense",
                                      date: DateTime.parse("01/12/2014"),
                                      user_id: 1
                                    },
                                    { name: "Internet",
                                      amount: 55,
                                      description: "High speed",
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("03/12/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 8.50,
                                      description: "Lunch special",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("02/12/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2400,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("11/12/2014"),
                                      user_id: 1
                                    },
                                    { name: "Bus pass",
                                      amount: 75,
                                      category_id: 4,
                                      type: "Expense",
                                      date: DateTime.parse("18/12/2014"),
                                      user_id: 1
                                    },
                                    { name: "Paycheck",
                                      amount: 2400,
                                      category_id: 6,
                                      type: "Income",
                                      date: DateTime.parse("05/12/2014"),
                                      user_id: 1
                                    },
                                    { name: "Lunch",
                                      amount: 11,
                                      description: "Tacos",
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("04/12/2014"),
                                      user_id: 1
                                    },
                                    { name: "New sweater",
                                      amount: 52,
                                      category_id: 7,
                                      type: "Expense",
                                      date: DateTime.parse("08/12/2014"),
                                      user_id: 1
                                    },
                                    { name: "Groceries",
                                      amount: 102,
                                      category_id: 3,
                                      type: "Expense",
                                      date: DateTime.parse("30/12/2014"),
                                      user_id: 1
                                    },
                                    { name: "Electrity",
                                      amount: 65,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("22/12/2014"),
                                      user_id: 1
                                    },
                                    { name: "Gas bill",
                                      amount: 75,
                                      category_id: 2,
                                      type: "Expense",
                                      date: DateTime.parse("25/12/2014"),
                                      user_id: 1
                                    },
                                    { name: "Christmas cash",
                                      amount: 200,
                                      category_id: 7,
                                      type: "Income",
                                      date: DateTime.parse("10/12/2014"),
                                      user_id: 1
                                    }
                                  ])
budget = Budget.create(name: "Peter's Budget", user_id: 1)

budget_items = BudgetItem.create([
                                    { amount: 1600,
                                      description: "Rent",
                                      category_id: 1,
                                      budget_id: 1,
                                      type: "Expense",
                                      duration_id: 1
                                    },
                                    { amount: 55,
                                      description: "Internet",
                                      category_id: 2,
                                      budget_id: 1,
                                      type: "Expense",
                                      duration_id: 1
                                    },
                                    { amount: 250,
                                      description: "Groceries",
                                      category_id: 3,
                                      type: "Expense",
                                      budget_id: 1
                                    },
                                    { amount: 65,
                                      description: "Electric bill",
                                      category_id: 2,
                                      budget_id: 1,
                                      type: "Expense",
                                      duration_id: 1
                                    },
                                    { amount: 75,
                                      description: "Bus pass",
                                      category_id: 4,
                                      budget_id: 1,
                                      type: "Expense",
                                      duration_id: 1
                                    },
                                    { amount: 20,
                                      description: "Lunch",
                                      category_id: 3,
                                      budget_id: 1,
                                      type: "Expense",
                                      duration_id: 2
                                    },
                                    { amount: 60,
                                      description: "For fun",
                                      category_id: 5,
                                      budget_id: 1,
                                      type: "Expense",
                                      duration_id: 1
                                    },
                                    { amount: 75,
                                      description: "Gas Bill",
                                      category_id: 2,
                                      budget_id: 1,
                                      type: "Expense",
                                      duration_id: 1
                                    },
                                    { amount: 4000,
                                      description: "Paychecks",
                                      category_id: 6,
                                      budget_id: 1,
                                      type: "Income",
                                      duration_id: 1
                                    }
                                  ])
